load_commands()
local function call(name, params)
  local response = dispatch(name, params or {})
  if response.error then error(name .. ": " .. response.error.message) end
  assert(response.result ~= nil, name .. " returned no result")
  print("PASS " .. name)
  return response.result
end
call("create_sprite", { width = 8, height = 8, color_mode = "rgba" })
call("add_layer", { name = "Test" })
call("put_pixel", { x = 1, y = 2, color = "#FF0000" })
local pixel = call("get_pixel", { x = 1, y = 2 })
assert(pixel.color == "#FF0000" or pixel.color == "#FF0000FF", json.encode(pixel))
call("put_pixels", { pixels = {{ x = 7, y = 7, color = "#00FF00" }} })
local green = call("get_pixel", { x = 7, y = 7 })
assert(green.color == "#00FF00" or green.color == "#00FF00FF", json.encode(green))
call("get_image_data", { format = "hex_array" })
call("select_rect", { x = 0, y = 0, width = 2, height = 2 })
call("get_selection")
call("deselect")
call("draw_rect", { x = 0, y = 0, width = 2, height = 2, color = "#0000FF", filled = true })
call("get_layers")
call("set_layer_opacity", { name = "Test", opacity = 200 })
call("get_palette", { max_colors = 4 })
call("generate_color_ramp", { base_color = "#FF8000", steps = 4 })
call("add_frame", { copy = true })
call("set_frame_duration", { frame = 2, duration_ms = 120 })
call("get_frames")
call("create_tag", { name = "Idle", from_frame = 1, to_frame = 2 })
call("get_tags")
call("get_color_stats")
call("compare_frames", { frame_a = 1, frame_b = 2 })
call("validate_animation")
local active_frame = app.frame.frameNumber
local preview = call("get_sprite_screenshot", { frame = 1 })
assert(preview.image and #preview.image > 10)
assert(app.frame.frameNumber == active_frame, "screenshot changed active frame")
local strip = call("get_animation_preview", { scale = 2, max_frames = 2 })
assert(strip.frame_count == 2 and strip.strip_width == 32)
call("get_sprite_info")
call("list_open_sprites")
call("execute_script", { code = "return { answer = 42 }" })
call("set_layer_opacity", { name = "Test", opacity = 150 })
call("undo")
call("redo")
call("create_tilemap_layer", { name = "Tiles", tile_width = 8, tile_height = 8 })
call("get_tilemap_info", { layer = "Tiles" })
call("create_slice", { name = "Body", x = 0, y = 0, width = 4, height = 4 })
call("get_slices")
call("create_character_template", { size = 8, animations = {{ name = "idle", frames = 2 }} })
call("create_tileset_template", { tile_size = 4, columns = 2, rows = 2 })
call("flip_sprite", { direction = "horizontal" })
call("rotate_sprite", { angle = 90 })
call("create_sprite", { width = 8, height = 8, color_mode = "rgba" })
call("put_pixel", { x = 1, y = 1, color = "#FF0000" })
call("add_frame", { copy = true })
call("interpolate_frames", { from_frame = 1, to_frame = 2, steps = 1 })
call("apply_dither", { color_a = "#FF0000", color_b = "#0000FF", pattern = "checker", x = 0, y = 0, width = 4, height = 4 })
local target = app.fs.joinPath(app.fs.tempPath, "voltage-aseprite-smoke")
app.fs.makeAllDirectories(target)
call("save_sprite", { path = app.fs.joinPath(target, "test.aseprite") })
call("export_png", { path = app.fs.joinPath(target, "test.png"), frame = 1 })
call("export_sprite_sheet", { path = app.fs.joinPath(target, "sheet.png"), json_path = app.fs.joinPath(target, "sheet.json") })
call("export_for_godot", { output_dir = target, name = "godot_test" })
assert(app.fs.isFile(app.fs.joinPath(target, "test.aseprite")))
assert(app.fs.isFile(app.fs.joinPath(target, "sheet.json")))
local metadata_file = assert(io.open(app.fs.joinPath(target, "sheet.json"), "r"))
local metadata = json.decode(metadata_file:read("*a"))
metadata_file:close()
assert(#metadata.frames == #app.sprite.frames, "sheet frame metadata is incomplete")
assert(metadata.frames[1].frame.w == 8 and metadata.frames[1].duration > 0)
local document = app.sprite
call("create_sprite", { width = 4, height = 4, color_mode = "rgba" })
local foreground = app.sprite
local scoped = call("get_sprite_info", { voltage_sprite_id = document.id })
assert(scoped.width == 8 and app.sprite == foreground, "stable targeting did not restore document")
print("VOLTAGE_ASEPRITE_SMOKE_OK")
